// Dutch professional clubs, seeded so Frontrow looks right the moment it starts
// — crest colours, city, stadium and the alias spellings the providers use.
//
// The Eredivisie colours are curated from club brand sources, not scraped:
// ESPN's own `color` field gets FC Groningen (returns white) and Fortuna (no
// green at all) plainly wrong, so an automated refresh must never overwrite
// these. NEC and Telstar are the two genuinely unresolved cases — third-party
// datasets disagree — and both are marked below; correct them in Instellingen
// and the app will remember.
//
// The sync engine can create a team it has never seen before (it happens with
// cup ties against amateur sides), so this list is a head start, not a fence.
// Colours are best-effort club brand colours; every one of them can be
// overridden per team in Instellingen, and the theme engine only ever uses
// them as an *input* — it clamps them into readable territory itself.

const NL = (o) => ({ country: 'NL', ...o });

export const TEAMS = [
  // ------------------------------------------------ Eredivisie 2026/27 (18)
  NL({ id: 'ajax', name: 'Ajax', full_name: 'AFC Ajax', short_name: 'Ajax', code: 'AJA',
       city: 'Amsterdam', stadium: 'Johan Cruijff ArenA', founded: 1900,
       primary_color: '#D2122E', secondary_color: '#FFFFFF',
       aliases: ['ajax', 'ajax amsterdam', 'afc ajax'] }),
  NL({ id: 'psv', name: 'PSV', full_name: 'PSV Eindhoven', short_name: 'PSV', code: 'PSV',
       city: 'Eindhoven', stadium: 'Philips Stadion', founded: 1913,
       primary_color: '#ED1C24', secondary_color: '#FFFFFF',
       aliases: ['psv', 'psv eindhoven'] }),
  NL({ id: 'feyenoord', name: 'Feyenoord', full_name: 'Feyenoord Rotterdam', short_name: 'Feyenoord', code: 'FEY',
       city: 'Rotterdam', stadium: 'De Kuip', founded: 1908,
       primary_color: '#E30613', secondary_color: '#FFFFFF',
       aliases: ['feyenoord', 'feyenoord rotterdam'] }),
  NL({ id: 'az', name: 'AZ', full_name: 'AZ Alkmaar', short_name: 'AZ', code: 'AZ',
       city: 'Alkmaar', stadium: 'AFAS Stadion', founded: 1967,
       primary_color: '#E30613', secondary_color: '#FFFFFF',
       aliases: ['az', 'az alkmaar', 'alkmaar zaanstreek'] }),
  NL({ id: 'twente', name: 'FC Twente', full_name: 'FC Twente', short_name: 'Twente', code: 'TWE',
       city: 'Enschede', stadium: 'De Grolsch Veste', founded: 1965,
       primary_color: '#E30613', secondary_color: '#FFFFFF',
       aliases: ['twente', 'fc twente', 'twente enschede'] }),
  NL({ id: 'utrecht', name: 'FC Utrecht', full_name: 'FC Utrecht', short_name: 'Utrecht', code: 'UTR',
       city: 'Utrecht', stadium: 'Stadion Galgenwaard', founded: 1970,
       primary_color: '#E30613', secondary_color: '#FFFFFF',
       aliases: ['utrecht', 'fc utrecht'] }),
  NL({ id: 'go_ahead_eagles', name: 'Go Ahead Eagles', full_name: 'Go Ahead Eagles', short_name: 'Go Ahead', code: 'GAE',
       city: 'Deventer', stadium: 'De Adelaarshorst', founded: 1902,
       primary_color: '#E4032E', secondary_color: '#FFE500',
       aliases: ['go ahead eagles', 'go ahead', 'gae'] }),
  // NEC: sources disagree (red+green, green+black, ESPN says red+light-blue).
  NL({ id: 'nec', name: 'NEC', full_name: 'NEC Nijmegen', short_name: 'NEC', code: 'NEC',
       city: 'Nijmegen', stadium: 'De Goffert', founded: 1900,
       primary_color: '#E30613', secondary_color: '#009036',
       aliases: ['nec', 'nec nijmegen', 'n e c'] }),
  NL({ id: 'heerenveen', name: 'sc Heerenveen', full_name: 'sc Heerenveen', short_name: 'Heerenveen', code: 'HEE',
       city: 'Heerenveen', stadium: 'Abe Lenstra Stadion', founded: 1920,
       primary_color: '#005CA9', secondary_color: '#E30613',
       aliases: ['heerenveen', 'sc heerenveen'] }),
  NL({ id: 'groningen', name: 'FC Groningen', full_name: 'FC Groningen', short_name: 'Groningen', code: 'GRO',
       city: 'Groningen', stadium: 'Euroborg', founded: 1971,
       primary_color: '#009B3A', secondary_color: '#FFFFFF',
       aliases: ['groningen', 'fc groningen'] }),
  NL({ id: 'sparta', name: 'Sparta Rotterdam', full_name: 'Sparta Rotterdam', short_name: 'Sparta', code: 'SPA',
       city: 'Rotterdam', stadium: 'Het Kasteel', founded: 1888,
       primary_color: '#E30613', secondary_color: '#FFFFFF',
       aliases: ['sparta', 'sparta rotterdam'] }),
  NL({ id: 'pec_zwolle', name: 'PEC Zwolle', full_name: 'PEC Zwolle', short_name: 'PEC Zwolle', code: 'PEC',
       city: 'Zwolle', stadium: 'MAC³PARK stadion', founded: 1910,
       primary_color: '#003DA5', secondary_color: '#FFFFFF',
       aliases: ['pec zwolle', 'zwolle', 'pec'] }),
  NL({ id: 'fortuna_sittard', name: 'Fortuna Sittard', full_name: 'Fortuna Sittard', short_name: 'Fortuna', code: 'FOR',
       city: 'Sittard', stadium: 'Fortuna Sittard Stadion', founded: 1968,
       primary_color: '#FFE600', secondary_color: '#009036',
       aliases: ['fortuna sittard', 'fortuna'] }),
  // Telstar: "de Witte Leeuwen" — white and blue; ESPN reports red and yellow.
  NL({ id: 'telstar', name: 'Telstar', full_name: 'SC Telstar', short_name: 'Telstar', code: 'TEL',
       city: 'Velsen-Zuid', stadium: 'BUKO Stadion', founded: 1963,
       primary_color: '#FFFFFF', secondary_color: '#005EB8',
       aliases: ['telstar', 'sc telstar'] }),
  NL({ id: 'excelsior', name: 'Excelsior', full_name: 'SBV Excelsior', short_name: 'Excelsior', code: 'EXC',
       city: 'Rotterdam', stadium: 'Van Donge & De Roo Stadion', founded: 1902,
       primary_color: '#E30613', secondary_color: '#000000',
       aliases: ['excelsior', 'sbv excelsior', 'excelsior rotterdam'] }),
  NL({ id: 'ado_den_haag', name: 'ADO Den Haag', full_name: 'ADO Den Haag', short_name: 'ADO', code: 'ADO',
       city: 'Den Haag', stadium: 'Bingoal Stadion', founded: 1905,
       primary_color: '#FFD500', secondary_color: '#007A33',
       aliases: ['ado den haag', 'ado', 'den haag'] }),
  NL({ id: 'cambuur', name: 'SC Cambuur', full_name: 'SC Cambuur Leeuwarden', short_name: 'Cambuur', code: 'CAM',
       city: 'Leeuwarden', stadium: 'Cambuur Stadion', founded: 1964,
       primary_color: '#FFE500', secondary_color: '#003DA5',
       aliases: ['cambuur', 'sc cambuur', 'cambuur leeuwarden'] }),
  NL({ id: 'willem_ii', name: 'Willem II', full_name: 'Willem II Tilburg', short_name: 'Willem II', code: 'WIL',
       city: 'Tilburg', stadium: 'Koning Willem II Stadion', founded: 1896,
       primary_color: '#E30613', secondary_color: '#003DA5',
       aliases: ['willem ii', 'willem 2', 'willem ii tilburg'] }),

  // ------------------------------- Keuken Kampioen Divisie 2026/27 (20) ----
  NL({ id: 'heracles', name: 'Heracles Almelo', full_name: 'Heracles Almelo', short_name: 'Heracles', code: 'HER',
       city: 'Almelo', stadium: 'Erve Asito', founded: 1903,
       primary_color: '#111111', secondary_color: '#FFFFFF',
       aliases: ['heracles', 'heracles almelo'] }),
  NL({ id: 'nac', name: 'NAC Breda', full_name: 'NAC Breda', short_name: 'NAC', code: 'NAC',
       city: 'Breda', stadium: 'Rat Verlegh Stadion', founded: 1912,
       primary_color: '#FFD200', secondary_color: '#111111',
       aliases: ['nac', 'nac breda'] }),
  NL({ id: 'volendam', name: 'FC Volendam', full_name: 'FC Volendam', short_name: 'Volendam', code: 'VOL',
       city: 'Volendam', stadium: 'Kras Stadion', founded: 1920,
       primary_color: '#F58220', secondary_color: '#111111',
       aliases: ['volendam', 'fc volendam'] }),
  NL({ id: 'vitesse', name: 'Vitesse', full_name: 'SBV Vitesse', short_name: 'Vitesse', code: 'VIT',
       city: 'Arnhem', stadium: 'GelreDome', founded: 1892,
       primary_color: '#FFE500', secondary_color: '#111111',
       aliases: ['vitesse', 'sbv vitesse', 'vitesse arnhem'] }),
  NL({ id: 'rkc', name: 'RKC Waalwijk', full_name: 'RKC Waalwijk', short_name: 'RKC', code: 'RKC',
       city: 'Waalwijk', stadium: 'Mandemakers Stadion', founded: 1940,
       primary_color: '#FFE500', secondary_color: '#004B93',
       aliases: ['rkc', 'rkc waalwijk', 'waalwijk'] }),
  NL({ id: 'de_graafschap', name: 'De Graafschap', full_name: 'De Graafschap', short_name: 'Graafschap', code: 'GRA',
       city: 'Doetinchem', stadium: 'De Vijverberg', founded: 1954,
       primary_color: '#0033A0', secondary_color: '#FFFFFF',
       aliases: ['de graafschap', 'graafschap'] }),
  NL({ id: 'roda_jc', name: 'Roda JC', full_name: 'Roda JC Kerkrade', short_name: 'Roda JC', code: 'ROD',
       city: 'Kerkrade', stadium: 'Parkstad Limburg Stadion', founded: 1962,
       primary_color: '#FFE500', secondary_color: '#111111',
       aliases: ['roda jc', 'roda', 'roda jc kerkrade'] }),
  NL({ id: 'mvv', name: 'MVV Maastricht', full_name: 'MVV Maastricht', short_name: 'MVV', code: 'MVV',
       city: 'Maastricht', stadium: 'De Geusselt', founded: 1902,
       primary_color: '#E30613', secondary_color: '#FFFFFF',
       aliases: ['mvv', 'mvv maastricht', 'maastricht'] }),
  NL({ id: 'fc_eindhoven', name: 'FC Eindhoven', full_name: 'FC Eindhoven', short_name: 'FC Eindhoven', code: 'EIN',
       city: 'Eindhoven', stadium: 'Jan Louwers Stadion', founded: 1909,
       primary_color: '#005BAC', secondary_color: '#FFFFFF',
       aliases: ['fc eindhoven', 'eindhoven'] }),
  NL({ id: 'den_bosch', name: 'FC Den Bosch', full_name: 'FC Den Bosch', short_name: 'Den Bosch', code: 'DBO',
       city: "'s-Hertogenbosch", stadium: 'Stadion De Vliert', founded: 1965,
       primary_color: '#005BAC', secondary_color: '#FFFFFF',
       aliases: ['fc den bosch', 'den bosch'] }),
  NL({ id: 'helmond_sport', name: 'Helmond Sport', full_name: 'Helmond Sport', short_name: 'Helmond', code: 'HEL',
       city: 'Helmond', stadium: 'De Braak', founded: 1967,
       primary_color: '#E30613', secondary_color: '#FFFFFF',
       aliases: ['helmond sport', 'helmond'] }),
  NL({ id: 'vvv', name: 'VVV-Venlo', full_name: 'VVV-Venlo', short_name: 'VVV', code: 'VVV',
       city: 'Venlo', stadium: 'Covebo Stadion De Koel', founded: 1903,
       primary_color: '#FFE500', secondary_color: '#111111',
       aliases: ['vvv', 'vvv venlo', 'venlo'] }),
  NL({ id: 'top_oss', name: 'TOP Oss', full_name: 'TOP Oss', short_name: 'TOP Oss', code: 'TOP',
       city: 'Oss', stadium: 'Frans Heesen Stadion', founded: 1928,
       primary_color: '#E30613', secondary_color: '#FFFFFF',
       aliases: ['top oss', 'oss'] }),
  NL({ id: 'dordrecht', name: 'FC Dordrecht', full_name: 'FC Dordrecht', short_name: 'Dordrecht', code: 'DOR',
       city: 'Dordrecht', stadium: 'Krommedijk', founded: 1883,
       primary_color: '#009639', secondary_color: '#FFFFFF',
       aliases: ['fc dordrecht', 'dordrecht'] }),
  NL({ id: 'emmen', name: 'FC Emmen', full_name: 'FC Emmen', short_name: 'Emmen', code: 'EMM',
       city: 'Emmen', stadium: 'De Oude Meerdijk', founded: 1925,
       primary_color: '#E30613', secondary_color: '#FFFFFF',
       aliases: ['fc emmen', 'emmen'] }),
  NL({ id: 'almere_city', name: 'Almere City', full_name: 'Almere City FC', short_name: 'Almere City', code: 'ALM',
       city: 'Almere', stadium: 'Yanmar Stadion', founded: 2001,
       primary_color: '#E30613', secondary_color: '#111111',
       aliases: ['almere city', 'almere city fc', 'almere'] }),
  NL({ id: 'jong_ajax', name: 'Jong Ajax', short_name: 'Jong Ajax', code: 'JAJ', city: 'Amsterdam',
       stadium: 'De Toekomst', primary_color: '#D2122E', secondary_color: '#FFFFFF',
       aliases: ['jong ajax', 'ajax ii', 'ajax u21'] }),
  NL({ id: 'jong_psv', name: 'Jong PSV', short_name: 'Jong PSV', code: 'JPS', city: 'Eindhoven',
       stadium: 'De Herdgang', primary_color: '#EE2223', secondary_color: '#FFFFFF',
       aliases: ['jong psv', 'psv ii', 'psv u21'] }),
  NL({ id: 'jong_az', name: 'Jong AZ', short_name: 'Jong AZ', code: 'JAZ', city: 'Wijdewormer',
       stadium: 'AFAS Trainingscomplex', primary_color: '#DA291C', secondary_color: '#FFFFFF',
       aliases: ['jong az', 'az ii', 'az u21'] }),
  NL({ id: 'jong_utrecht', name: 'Jong FC Utrecht', short_name: 'Jong Utrecht', code: 'JUT', city: 'Utrecht',
       stadium: 'Sportcomplex Zoudenbalch', primary_color: '#C8102E', secondary_color: '#111111',
       aliases: ['jong fc utrecht', 'jong utrecht', 'utrecht ii'] }),

  // ------------------------------------------------------ national teams ---
  { id: 'nederland', name: 'Nederland', full_name: 'Nederlands elftal', short_name: 'Nederland', code: 'NED',
    country: 'NL', is_national: 1, city: 'Zeist', stadium: 'Johan Cruijff ArenA',
    primary_color: '#F36C21', secondary_color: '#004B93',
    aliases: ['nederland', 'netherlands', 'holland', 'nederlands elftal', 'oranje', 'ned'] },
];

export default TEAMS;
